### PR TITLE
Hack for py3k support (#2)

### PR DESCRIPTION
**Pull request by notpushkin**
I can't think of a cleaner solution, so here it goes.

### CODE REVIEW

**Comment by liclac** [comment]
Is this a workaround for `u""` not working pre-3.4? I'm not sure what exactly you're trying to accomplish with `_u()`…

Also have a look at [six](http://pythonhosted.org/six/), chances are it has what you need.

**Comment by notpushkin** [comment]
Not really. The thing is that `jwt.encode` seems to return bytestrings on both Python 2 and 3, yet in Python 3 the `json` module doesn't support encoding `bytes` objects (see #2).

I haven't found anything related in Six, although the [`six.u`](https://pythonhosted.org/six/#six.u) function seemed to do what needed at first.

The `_u` function calls "decode" method on its argument, if available, thus providing `str` on py3, so the JSON encoder would allow it. I agree that the name is way too ambiguous, I'd rather rename it (but I have no idea about how to name it).

Another approach would be to override [`json.JSONEncoder.default`](https://docs.python.org/3.5/library/json.html#json.JSONEncoder.default) method in a subclass, but it would be an overkill I think.

**Comment by liclac** [comment]
Ah!

This honestly sounds like a bug in the `jwt` library, but changing that function to something like this would suffice as a stopgap solution:

``` python
def to_str(s):
    return s.decode() if 'decode' in s else s
```

**Comment by notpushkin** [comment]
I've also just noticed that on py2 `s.decode()` would produce `unicode`. Shouldn't be a problem, though, as it still would be JSON-encoded correctly.

**Pull request closed without merging**
